//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latte.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LatteParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ILatteListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LatteParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LatteParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopDef([NotNull] LatteParser.TopDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopDef([NotNull] LatteParser.TopDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] LatteParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] LatteParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LatteParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LatteParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty([NotNull] LatteParser.EmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty([NotNull] LatteParser.EmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] LatteParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] LatteParser.BlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decl</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecl([NotNull] LatteParser.DeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decl</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecl([NotNull] LatteParser.DeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Ass</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAss([NotNull] LatteParser.AssContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Ass</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAss([NotNull] LatteParser.AssContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Incr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncr([NotNull] LatteParser.IncrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Incr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncr([NotNull] LatteParser.IncrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecr([NotNull] LatteParser.DecrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecr([NotNull] LatteParser.DecrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Ret</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRet([NotNull] LatteParser.RetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Ret</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRet([NotNull] LatteParser.RetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VRet</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVRet([NotNull] LatteParser.VRetContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VRet</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVRet([NotNull] LatteParser.VRetContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCond([NotNull] LatteParser.CondContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCond([NotNull] LatteParser.CondContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CondElse</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondElse([NotNull] LatteParser.CondElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CondElse</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondElse([NotNull] LatteParser.CondElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] LatteParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] LatteParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SExp</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExp([NotNull] LatteParser.SExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SExp</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExp([NotNull] LatteParser.SExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] LatteParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] LatteParser.IntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Str</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr([NotNull] LatteParser.StrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Str</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr([NotNull] LatteParser.StrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Bool</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] LatteParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Bool</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] LatteParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Void</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVoid([NotNull] LatteParser.VoidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Void</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVoid([NotNull] LatteParser.VoidContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleDecl</c>
	/// labeled alternative in <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDecl([NotNull] LatteParser.SimpleDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleDecl</c>
	/// labeled alternative in <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDecl([NotNull] LatteParser.SimpleDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AssDecl</c>
	/// labeled alternative in <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssDecl([NotNull] LatteParser.AssDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssDecl</c>
	/// labeled alternative in <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssDecl([NotNull] LatteParser.AssDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EId</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEId([NotNull] LatteParser.EIdContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EId</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEId([NotNull] LatteParser.EIdContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EFunCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEFunCall([NotNull] LatteParser.EFunCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EFunCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEFunCall([NotNull] LatteParser.EFunCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ERelOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterERelOp([NotNull] LatteParser.ERelOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ERelOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitERelOp([NotNull] LatteParser.ERelOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ETrue</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterETrue([NotNull] LatteParser.ETrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ETrue</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitETrue([NotNull] LatteParser.ETrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EOr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEOr([NotNull] LatteParser.EOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EOr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEOr([NotNull] LatteParser.EOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEInt([NotNull] LatteParser.EIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEInt([NotNull] LatteParser.EIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EUnOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEUnOp([NotNull] LatteParser.EUnOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EUnOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEUnOp([NotNull] LatteParser.EUnOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EStr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEStr([NotNull] LatteParser.EStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EStr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEStr([NotNull] LatteParser.EStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EMulOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEMulOp([NotNull] LatteParser.EMulOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EMulOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEMulOp([NotNull] LatteParser.EMulOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEAnd([NotNull] LatteParser.EAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEAnd([NotNull] LatteParser.EAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEParen([NotNull] LatteParser.EParenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEParen([NotNull] LatteParser.EParenContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EFalse</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEFalse([NotNull] LatteParser.EFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EFalse</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEFalse([NotNull] LatteParser.EFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EAddOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEAddOp([NotNull] LatteParser.EAddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EAddOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEAddOp([NotNull] LatteParser.EAddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOp([NotNull] LatteParser.AddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOp([NotNull] LatteParser.AddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulOp([NotNull] LatteParser.MulOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulOp([NotNull] LatteParser.MulOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelOp([NotNull] LatteParser.RelOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelOp([NotNull] LatteParser.RelOpContext context);
}
