//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latte.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LatteParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ILatteVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LatteParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TopDefFunction</c>
	/// labeled alternative in <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopDefFunction([NotNull] LatteParser.TopDefFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TopDefClass</c>
	/// labeled alternative in <see cref="LatteParser.topDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopDefClass([NotNull] LatteParser.TopDefClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] LatteParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LatteParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty([NotNull] LatteParser.EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] LatteParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decl</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecl([NotNull] LatteParser.DeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Ass</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAss([NotNull] LatteParser.AssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Incr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncr([NotNull] LatteParser.IncrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decr</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecr([NotNull] LatteParser.DecrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Ret</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRet([NotNull] LatteParser.RetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VRet</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVRet([NotNull] LatteParser.VRetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Cond</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond([NotNull] LatteParser.CondContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CondElse</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondElse([NotNull] LatteParser.CondElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] LatteParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SExp</c>
	/// labeled alternative in <see cref="LatteParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExp([NotNull] LatteParser.SExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdLhs</c>
	/// labeled alternative in <see cref="LatteParser.lhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdLhs([NotNull] LatteParser.IdLhsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FieldAccessLHS</c>
	/// labeled alternative in <see cref="LatteParser.lhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccessLHS([NotNull] LatteParser.FieldAccessLHSContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] LatteParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] LatteParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Str</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr([NotNull] LatteParser.StrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bool</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] LatteParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Void</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVoid([NotNull] LatteParser.VoidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassInstance</c>
	/// labeled alternative in <see cref="LatteParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstance([NotNull] LatteParser.ClassInstanceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SimpleDecl</c>
	/// labeled alternative in <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleDecl([NotNull] LatteParser.SimpleDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssDecl</c>
	/// labeled alternative in <see cref="LatteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssDecl([NotNull] LatteParser.AssDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EId</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEId([NotNull] LatteParser.EIdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EFunCall</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEFunCall([NotNull] LatteParser.EFunCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ERelOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitERelOp([NotNull] LatteParser.ERelOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ETrue</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitETrue([NotNull] LatteParser.ETrueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EOr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEOr([NotNull] LatteParser.EOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEInt([NotNull] LatteParser.EIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EUnOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEUnOp([NotNull] LatteParser.EUnOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EStr</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEStr([NotNull] LatteParser.EStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EFieldAccessRHS</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEFieldAccessRHS([NotNull] LatteParser.EFieldAccessRHSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EMulOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEMulOp([NotNull] LatteParser.EMulOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEAnd([NotNull] LatteParser.EAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEParen([NotNull] LatteParser.EParenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EFalse</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEFalse([NotNull] LatteParser.EFalseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ENew</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitENew([NotNull] LatteParser.ENewContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EAddOp</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEAddOp([NotNull] LatteParser.EAddOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ENull</c>
	/// labeled alternative in <see cref="LatteParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitENull([NotNull] LatteParser.ENullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.fieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccess([NotNull] LatteParser.FieldAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOp([NotNull] LatteParser.AddOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulOp([NotNull] LatteParser.MulOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatteParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelOp([NotNull] LatteParser.RelOpContext context);
}
