//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latte.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class LatteParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, COMMENT=34, MULTICOMMENT=35, INT=36, ID=37, WS=38, 
		STR=39;
	public const int
		RULE_program = 0, RULE_topDef = 1, RULE_arg = 2, RULE_block = 3, RULE_stmt = 4, 
		RULE_type_ = 5, RULE_item = 6, RULE_expr = 7, RULE_addOp = 8, RULE_mulOp = 9, 
		RULE_relOp = 10;
	public static readonly string[] ruleNames = {
		"program", "topDef", "arg", "block", "stmt", "type_", "item", "expr", 
		"addOp", "mulOp", "relOp"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "','", "'{'", "'}'", "';'", "'='", "'++'", "'--'", 
		"'return'", "'if'", "'else'", "'while'", "'int'", "'string'", "'boolean'", 
		"'void'", "'-'", "'!'", "'&&'", "'||'", "'true'", "'false'", "'+'", "'*'", 
		"'/'", "'%'", "'<'", "'<='", "'>'", "'>='", "'=='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "COMMENT", 
		"MULTICOMMENT", "INT", "ID", "WS", "STR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Latte.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LatteParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LatteParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LatteParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TopDefContext[] topDef() {
			return GetRuleContexts<TopDefContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TopDefContext topDef(int i) {
			return GetRuleContext<TopDefContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 23;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 22;
				topDef();
				}
				}
				State = 25;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( ((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TopDefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext arg() {
			return GetRuleContext<ArgContext>(0);
		}
		public TopDefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_topDef; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterTopDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitTopDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTopDef(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TopDefContext topDef() {
		TopDefContext _localctx = new TopDefContext(Context, State);
		EnterRule(_localctx, 2, RULE_topDef);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 27;
			type_();
			State = 28;
			Match(ID);
			State = 29;
			Match(T__0);
			State = 31;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (((_la) & ~0x3f) == 0 && ((1L << _la) & 245760L) != 0) {
				{
				State = 30;
				arg();
				}
			}

			State = 33;
			Match(T__1);
			State = 34;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context[] type_() {
			return GetRuleContexts<Type_Context>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_(int i) {
			return GetRuleContext<Type_Context>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(LatteParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(LatteParser.ID, i);
		}
		public ArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgContext arg() {
		ArgContext _localctx = new ArgContext(Context, State);
		EnterRule(_localctx, 4, RULE_arg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			type_();
			State = 37;
			Match(ID);
			State = 44;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 38;
				Match(T__2);
				State = 39;
				type_();
				State = 40;
				Match(ID);
				}
				}
				State = 46;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 6, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			Match(T__3);
			State = 51;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 755927870546L) != 0) {
				{
				{
				State = 48;
				stmt();
				}
				}
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 54;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
	 
		public StmtContext() { }
		public virtual void CopyFrom(StmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AssContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterAss(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitAss(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAss(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DecrContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public DecrContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterDecr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitDecr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDecr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RetContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RetContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EmptyContext : StmtContext {
		public EmptyContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEmpty(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CondContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public CondContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterCond(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitCond(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCond(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CondElseContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public CondElseContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterCondElse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitCondElse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondElse(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VRetContext : StmtContext {
		public VRetContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterVRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitVRet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVRet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IncrContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public IncrContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterIncr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitIncr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BlockStmtContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public BlockStmtContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterBlockStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitBlockStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DeclContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ItemContext[] item() {
			return GetRuleContexts<ItemContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ItemContext item(int i) {
			return GetRuleContext<ItemContext>(i);
		}
		public DeclContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public WhileContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterWhile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitWhile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SExpContext : StmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public SExpContext(StmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterSExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitSExp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 8, RULE_stmt);
		int _la;
		try {
			State = 109;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				_localctx = new EmptyContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 56;
				Match(T__5);
				}
				break;
			case 2:
				_localctx = new BlockStmtContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 57;
				block();
				}
				break;
			case 3:
				_localctx = new DeclContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 58;
				type_();
				State = 59;
				item();
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__2) {
					{
					{
					State = 60;
					Match(T__2);
					State = 61;
					item();
					}
					}
					State = 66;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 67;
				Match(T__5);
				}
				break;
			case 4:
				_localctx = new AssContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 69;
				Match(ID);
				State = 70;
				Match(T__6);
				State = 71;
				expr(0);
				State = 72;
				Match(T__5);
				}
				break;
			case 5:
				_localctx = new IncrContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 74;
				Match(ID);
				State = 75;
				Match(T__7);
				State = 76;
				Match(T__5);
				}
				break;
			case 6:
				_localctx = new DecrContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 77;
				Match(ID);
				State = 78;
				Match(T__8);
				State = 79;
				Match(T__5);
				}
				break;
			case 7:
				_localctx = new RetContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 80;
				Match(T__9);
				State = 81;
				expr(0);
				State = 82;
				Match(T__5);
				}
				break;
			case 8:
				_localctx = new VRetContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 84;
				Match(T__9);
				State = 85;
				Match(T__5);
				}
				break;
			case 9:
				_localctx = new CondContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 86;
				Match(T__10);
				State = 87;
				Match(T__0);
				State = 88;
				expr(0);
				State = 89;
				Match(T__1);
				State = 90;
				stmt();
				}
				break;
			case 10:
				_localctx = new CondElseContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 92;
				Match(T__10);
				State = 93;
				Match(T__0);
				State = 94;
				expr(0);
				State = 95;
				Match(T__1);
				State = 96;
				stmt();
				State = 97;
				Match(T__11);
				State = 98;
				stmt();
				}
				break;
			case 11:
				_localctx = new WhileContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 100;
				Match(T__12);
				State = 101;
				Match(T__0);
				State = 102;
				expr(0);
				State = 103;
				Match(T__1);
				State = 104;
				stmt();
				}
				break;
			case 12:
				_localctx = new SExpContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 106;
				expr(0);
				State = 107;
				Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_Context : ParserRuleContext {
		public Type_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_; } }
	 
		public Type_Context() { }
		public virtual void CopyFrom(Type_Context context) {
			base.CopyFrom(context);
		}
	}
	public partial class StrContext : Type_Context {
		public StrContext(Type_Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolContext : Type_Context {
		public BoolContext(Type_Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterBool(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitBool(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VoidContext : Type_Context {
		public VoidContext(Type_Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterVoid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitVoid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVoid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntContext : Type_Context {
		public IntContext(Type_Context context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_Context type_() {
		Type_Context _localctx = new Type_Context(Context, State);
		EnterRule(_localctx, 10, RULE_type_);
		try {
			State = 115;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__13:
				_localctx = new IntContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 111;
				Match(T__13);
				}
				break;
			case T__14:
				_localctx = new StrContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 112;
				Match(T__14);
				}
				break;
			case T__15:
				_localctx = new BoolContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 113;
				Match(T__15);
				}
				break;
			case T__16:
				_localctx = new VoidContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 114;
				Match(T__16);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ItemContext : ParserRuleContext {
		public ItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_item; } }
	 
		public ItemContext() { }
		public virtual void CopyFrom(ItemContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class SimpleDeclContext : ItemContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public SimpleDeclContext(ItemContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterSimpleDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitSimpleDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimpleDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AssDeclContext : ItemContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssDeclContext(ItemContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterAssDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitAssDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ItemContext item() {
		ItemContext _localctx = new ItemContext(Context, State);
		EnterRule(_localctx, 12, RULE_item);
		try {
			State = 121;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				_localctx = new SimpleDeclContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 117;
				Match(ID);
				}
				break;
			case 2:
				_localctx = new AssDeclContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 118;
				Match(ID);
				State = 119;
				Match(T__6);
				State = 120;
				expr(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class EIdContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		public EIdContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEId(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EFunCallContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LatteParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EFunCallContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEFunCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEFunCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEFunCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ERelOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelOpContext relOp() {
			return GetRuleContext<RelOpContext>(0);
		}
		public ERelOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterERelOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitERelOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitERelOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ETrueContext : ExprContext {
		public ETrueContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterETrue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitETrue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitETrue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EOrContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EOrContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEOr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEOr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEOr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EIntContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LatteParser.INT, 0); }
		public EIntContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EUnOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public EUnOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEUnOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEUnOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEUnOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EStrContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STR() { return GetToken(LatteParser.STR, 0); }
		public EStrContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEStr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEStr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EMulOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulOpContext mulOp() {
			return GetRuleContext<MulOpContext>(0);
		}
		public EMulOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEMulOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEMulOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEMulOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EAndContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public EAndContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEAnd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEAnd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEAnd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EParenContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public EParenContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEParen(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEParen(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEParen(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EFalseContext : ExprContext {
		public EFalseContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEFalse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEFalse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEFalse(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EAddOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddOpContext addOp() {
			return GetRuleContext<AddOpContext>(0);
		}
		public EAddOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterEAddOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitEAddOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEAddOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 14;
		EnterRecursionRule(_localctx, 14, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				_localctx = new EUnOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 124;
				_la = TokenStream.LA(1);
				if ( !(_la==T__17 || _la==T__18) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 125;
				expr(13);
				}
				break;
			case 2:
				{
				_localctx = new EIdContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 126;
				Match(ID);
				}
				break;
			case 3:
				{
				_localctx = new EIntContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 127;
				Match(INT);
				}
				break;
			case 4:
				{
				_localctx = new ETrueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 128;
				Match(T__21);
				}
				break;
			case 5:
				{
				_localctx = new EFalseContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 129;
				Match(T__22);
				}
				break;
			case 6:
				{
				_localctx = new EFunCallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 130;
				Match(ID);
				State = 131;
				Match(T__0);
				State = 140;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (((_la) & ~0x3f) == 0 && ((1L << _la) & 755927613442L) != 0) {
					{
					State = 132;
					expr(0);
					State = 137;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__2) {
						{
						{
						State = 133;
						Match(T__2);
						State = 134;
						expr(0);
						}
						}
						State = 139;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 142;
				Match(T__1);
				}
				break;
			case 7:
				{
				_localctx = new EStrContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 143;
				Match(STR);
				}
				break;
			case 8:
				{
				_localctx = new EParenContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 144;
				Match(T__0);
				State = 145;
				expr(0);
				State = 146;
				Match(T__1);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 170;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 168;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
					case 1:
						{
						_localctx = new EMulOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 150;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 151;
						mulOp();
						State = 152;
						expr(13);
						}
						break;
					case 2:
						{
						_localctx = new EAddOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 154;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 155;
						addOp();
						State = 156;
						expr(12);
						}
						break;
					case 3:
						{
						_localctx = new ERelOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 158;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 159;
						relOp();
						State = 160;
						expr(11);
						}
						break;
					case 4:
						{
						_localctx = new EAndContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 162;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 163;
						Match(T__19);
						State = 164;
						expr(9);
						}
						break;
					case 5:
						{
						_localctx = new EOrContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 165;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 166;
						Match(T__20);
						State = 167;
						expr(8);
						}
						break;
					}
					} 
				}
				State = 172;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AddOpContext : ParserRuleContext {
		public AddOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterAddOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitAddOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddOpContext addOp() {
		AddOpContext _localctx = new AddOpContext(Context, State);
		EnterRule(_localctx, 16, RULE_addOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			_la = TokenStream.LA(1);
			if ( !(_la==T__17 || _la==T__23) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulOpContext : ParserRuleContext {
		public MulOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterMulOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitMulOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMulOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MulOpContext mulOp() {
		MulOpContext _localctx = new MulOpContext(Context, State);
		EnterRule(_localctx, 18, RULE_mulOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 175;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 234881024L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelOpContext : ParserRuleContext {
		public RelOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.EnterRelOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILatteListener typedListener = listener as ILatteListener;
			if (typedListener != null) typedListener.ExitRelOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILatteVisitor<TResult> typedVisitor = visitor as ILatteVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelOpContext relOp() {
		RelOpContext _localctx = new RelOpContext(Context, State);
		EnterRule(_localctx, 20, RULE_relOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 177;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 16911433728L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 7: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 12);
		case 1: return Precpred(Context, 11);
		case 2: return Precpred(Context, 10);
		case 3: return Precpred(Context, 9);
		case 4: return Precpred(Context, 8);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,39,180,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,4,0,24,8,0,11,0,12,0,25,1,1,1,1,1,1,
		1,1,3,1,32,8,1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,5,2,43,8,2,10,2,12,
		2,46,9,2,1,3,1,3,5,3,50,8,3,10,3,12,3,53,9,3,1,3,1,3,1,4,1,4,1,4,1,4,1,
		4,1,4,5,4,63,8,4,10,4,12,4,66,9,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,
		1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,110,
		8,4,1,5,1,5,1,5,1,5,3,5,116,8,5,1,6,1,6,1,6,1,6,3,6,122,8,6,1,7,1,7,1,
		7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,5,7,136,8,7,10,7,12,7,139,9,7,3,
		7,141,8,7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,149,8,7,1,7,1,7,1,7,1,7,1,7,1,7,
		1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,5,7,169,8,7,10,7,12,7,
		172,9,7,1,8,1,8,1,9,1,9,1,10,1,10,1,10,0,1,14,11,0,2,4,6,8,10,12,14,16,
		18,20,0,4,1,0,18,19,2,0,18,18,24,24,1,0,25,27,1,0,28,33,202,0,23,1,0,0,
		0,2,27,1,0,0,0,4,36,1,0,0,0,6,47,1,0,0,0,8,109,1,0,0,0,10,115,1,0,0,0,
		12,121,1,0,0,0,14,148,1,0,0,0,16,173,1,0,0,0,18,175,1,0,0,0,20,177,1,0,
		0,0,22,24,3,2,1,0,23,22,1,0,0,0,24,25,1,0,0,0,25,23,1,0,0,0,25,26,1,0,
		0,0,26,1,1,0,0,0,27,28,3,10,5,0,28,29,5,37,0,0,29,31,5,1,0,0,30,32,3,4,
		2,0,31,30,1,0,0,0,31,32,1,0,0,0,32,33,1,0,0,0,33,34,5,2,0,0,34,35,3,6,
		3,0,35,3,1,0,0,0,36,37,3,10,5,0,37,44,5,37,0,0,38,39,5,3,0,0,39,40,3,10,
		5,0,40,41,5,37,0,0,41,43,1,0,0,0,42,38,1,0,0,0,43,46,1,0,0,0,44,42,1,0,
		0,0,44,45,1,0,0,0,45,5,1,0,0,0,46,44,1,0,0,0,47,51,5,4,0,0,48,50,3,8,4,
		0,49,48,1,0,0,0,50,53,1,0,0,0,51,49,1,0,0,0,51,52,1,0,0,0,52,54,1,0,0,
		0,53,51,1,0,0,0,54,55,5,5,0,0,55,7,1,0,0,0,56,110,5,6,0,0,57,110,3,6,3,
		0,58,59,3,10,5,0,59,64,3,12,6,0,60,61,5,3,0,0,61,63,3,12,6,0,62,60,1,0,
		0,0,63,66,1,0,0,0,64,62,1,0,0,0,64,65,1,0,0,0,65,67,1,0,0,0,66,64,1,0,
		0,0,67,68,5,6,0,0,68,110,1,0,0,0,69,70,5,37,0,0,70,71,5,7,0,0,71,72,3,
		14,7,0,72,73,5,6,0,0,73,110,1,0,0,0,74,75,5,37,0,0,75,76,5,8,0,0,76,110,
		5,6,0,0,77,78,5,37,0,0,78,79,5,9,0,0,79,110,5,6,0,0,80,81,5,10,0,0,81,
		82,3,14,7,0,82,83,5,6,0,0,83,110,1,0,0,0,84,85,5,10,0,0,85,110,5,6,0,0,
		86,87,5,11,0,0,87,88,5,1,0,0,88,89,3,14,7,0,89,90,5,2,0,0,90,91,3,8,4,
		0,91,110,1,0,0,0,92,93,5,11,0,0,93,94,5,1,0,0,94,95,3,14,7,0,95,96,5,2,
		0,0,96,97,3,8,4,0,97,98,5,12,0,0,98,99,3,8,4,0,99,110,1,0,0,0,100,101,
		5,13,0,0,101,102,5,1,0,0,102,103,3,14,7,0,103,104,5,2,0,0,104,105,3,8,
		4,0,105,110,1,0,0,0,106,107,3,14,7,0,107,108,5,6,0,0,108,110,1,0,0,0,109,
		56,1,0,0,0,109,57,1,0,0,0,109,58,1,0,0,0,109,69,1,0,0,0,109,74,1,0,0,0,
		109,77,1,0,0,0,109,80,1,0,0,0,109,84,1,0,0,0,109,86,1,0,0,0,109,92,1,0,
		0,0,109,100,1,0,0,0,109,106,1,0,0,0,110,9,1,0,0,0,111,116,5,14,0,0,112,
		116,5,15,0,0,113,116,5,16,0,0,114,116,5,17,0,0,115,111,1,0,0,0,115,112,
		1,0,0,0,115,113,1,0,0,0,115,114,1,0,0,0,116,11,1,0,0,0,117,122,5,37,0,
		0,118,119,5,37,0,0,119,120,5,7,0,0,120,122,3,14,7,0,121,117,1,0,0,0,121,
		118,1,0,0,0,122,13,1,0,0,0,123,124,6,7,-1,0,124,125,7,0,0,0,125,149,3,
		14,7,13,126,149,5,37,0,0,127,149,5,36,0,0,128,149,5,22,0,0,129,149,5,23,
		0,0,130,131,5,37,0,0,131,140,5,1,0,0,132,137,3,14,7,0,133,134,5,3,0,0,
		134,136,3,14,7,0,135,133,1,0,0,0,136,139,1,0,0,0,137,135,1,0,0,0,137,138,
		1,0,0,0,138,141,1,0,0,0,139,137,1,0,0,0,140,132,1,0,0,0,140,141,1,0,0,
		0,141,142,1,0,0,0,142,149,5,2,0,0,143,149,5,39,0,0,144,145,5,1,0,0,145,
		146,3,14,7,0,146,147,5,2,0,0,147,149,1,0,0,0,148,123,1,0,0,0,148,126,1,
		0,0,0,148,127,1,0,0,0,148,128,1,0,0,0,148,129,1,0,0,0,148,130,1,0,0,0,
		148,143,1,0,0,0,148,144,1,0,0,0,149,170,1,0,0,0,150,151,10,12,0,0,151,
		152,3,18,9,0,152,153,3,14,7,13,153,169,1,0,0,0,154,155,10,11,0,0,155,156,
		3,16,8,0,156,157,3,14,7,12,157,169,1,0,0,0,158,159,10,10,0,0,159,160,3,
		20,10,0,160,161,3,14,7,11,161,169,1,0,0,0,162,163,10,9,0,0,163,164,5,20,
		0,0,164,169,3,14,7,9,165,166,10,8,0,0,166,167,5,21,0,0,167,169,3,14,7,
		8,168,150,1,0,0,0,168,154,1,0,0,0,168,158,1,0,0,0,168,162,1,0,0,0,168,
		165,1,0,0,0,169,172,1,0,0,0,170,168,1,0,0,0,170,171,1,0,0,0,171,15,1,0,
		0,0,172,170,1,0,0,0,173,174,7,1,0,0,174,17,1,0,0,0,175,176,7,2,0,0,176,
		19,1,0,0,0,177,178,7,3,0,0,178,21,1,0,0,0,13,25,31,44,51,64,109,115,121,
		137,140,148,168,170
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
